/**
 * QR Code Provisioning Payload Structure
 *
 * This interface defines the structure of the JSON payload embedded in
 * camp provisioning QR codes. The QR code is generated by the backend
 * when staff initiates a sync provisioning session.
 *
 * @example
 * {
 *   "serverUrls": [
 *     "http://192.168.1.100:3000",  // Ethernet IP
 *     "http://192.168.43.1:3000",   // AP Mode IP
 *     "http://camp.local:3000"      // mDNS hostname
 *   ],
 *   "syncCode": "ABC123XYZ",         // Short-lived code (expires in 15 minutes)
 *   "campId": "camp-uuid-1234"       // Camp identifier
 * }
 */
export interface QRPayload {
  /**
   * Array of server URLs to try sequentially.
   * Multiple URLs are provided because the Raspberry Pi may have
   * multiple network interfaces (Ethernet, WiFi AP, mDNS).
   * The app tests each URL until one succeeds.
   */
  serverUrls: string[];

  /**
   * Short-lived synchronization code (typically 15-minute expiry).
   * This code is exchanged for a temporary sync token via
   * POST /api/auth/camp/exchange endpoint.
   * One-time use - consumed after successful token exchange.
   */
  syncCode: string;

  /**
   * Unique identifier for the camp.
   * Used for data isolation and camp-specific operations.
   */
  campId: string;
}

/**
 * Result of QR provisioning operation
 */
export interface ProvisioningResult {
  /**
   * Whether the provisioning operation completed successfully
   */
  success: boolean;

  /**
   * Human-readable error message (Afrikaans for user display)
   */
  error?: string;

  /**
   * Successfully connected base URL (if success)
   */
  baseUrl?: string;

  /**
   * Camp ID from QR payload (if success)
   */
  campId?: string;
}
