/**
 * WiFi Configuration for Auto-Connection
 *
 * WiFi credentials embedded in QR code to enable automatic
 * connection to camp network without manual WiFi setup.
 */
export interface WiFiConfig {
  /**
   * Network SSID (e.g., "SuidlandersKamp")
   */
  ssid: string;

  /**
   * WiFi password
   */
  password: string;

  /**
   * Security type: WPA2, WPA3, WEP, NONE
   * Default: WPA2 (most common)
   */
  security?: 'WPA2' | 'WPA3' | 'WEP' | 'NONE';
}

/**
 * QR Code Provisioning Payload Structure
 *
 * This interface defines the structure of the JSON payload embedded in
 * camp provisioning QR codes. The QR code is generated by the backend
 * when staff initiates a sync provisioning session.
 *
 * @example
 * {
 *   "wifi": {
 *     "ssid": "SuidlandersKamp",
 *     "password": "Kamp2026!",
 *     "security": "WPA2"
 *   },
 *   "serverUrls": [
 *     "http://192.168.4.1:3000",    // WiFi AP IP
 *     "http://camp.local:3000"      // mDNS hostname
 *   ],
 *   "syncCode": "ABC123XYZ",         // Short-lived code (expires in 15 minutes)
 *   "campId": "camp-uuid-1234"       // Camp identifier
 * }
 */
export interface QRPayload {
  /**
   * WiFi configuration for automatic network connection.
   * When present, the app will automatically connect to this
   * WiFi network before attempting server sync.
   */
  wifi: WiFiConfig;

  /**
   * Array of server URLs to try sequentially.
   * Multiple URLs are provided because the Raspberry Pi may have
   * multiple network interfaces (Ethernet, WiFi AP, mDNS).
   * The app tests each URL until one succeeds.
   */
  serverUrls: string[];

  /**
   * Short-lived synchronization code (typically 15-minute expiry).
   * This code is exchanged for a temporary sync token via
   * POST /api/auth/camp/exchange endpoint.
   * One-time use - consumed after successful token exchange.
   */
  syncCode: string;

  /**
   * Unique identifier for the camp.
   * Used for data isolation and camp-specific operations.
   */
  campId: string;
}

/**
 * Result of QR provisioning operation
 */
export interface ProvisioningResult {
  /**
   * Whether the provisioning operation completed successfully
   */
  success: boolean;

  /**
   * Human-readable error message (Afrikaans for user display)
   */
  error?: string;

  /**
   * Successfully connected base URL (if success)
   */
  baseUrl?: string;

  /**
   * Camp ID from QR payload (if success)
   */
  campId?: string;
}
